# Generated by Django 2.2.3 on 2019-07-28 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_auto_20190728_1011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together={('user_id', 'friend_id')},
        ),
    ]
